syn keyword cType EG_INT EG_CHAR EG_UCHAR EG_UINT EG_SHORT EG_USHORT
syn keyword cType EG_CAMERA EG_MAP EG_MPOS EG_FILEF EG_OBJECT
syn keyword cType EG_RECT EG_MAPL
syn keyword cType EG_ANIM2D EG_LANIM EG_FRAME EG_CREDIT EG_CHEAT EG_CHEAT_CODE 
